### ISSUE TITLE
Submit Mini-Project Proposal in .pdf format & Presentation Slide in .pptx Format

### ISSUE THREAD

**Issue by ErSKS** [KhCE/C#1]
All the students of BE Computer I Year / I Part are requested to submit their Mini-Project Proposal in .pdf Format & Presentation Slide in .pptx Format.

Email: computer.khwopa@gmail.com

**Comment by ghost** [comment]
Blood Management System....
Me and my entire group members are so sorry for late and make you
disappoint . But due to some problems we are unable to submit our proposal
and power point in time that you had given to us.
